CREATE TABLE BR_MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    MEMBER_BIRTHDAY DATE NOT NULL,
    MEMBER_GENDER CHAR(6),
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(150)
);

DROP TABLE BR_MEMBER_TBL;

CREATE TABLE BR_MENU_TBL(
    CATEGORY VARCHAR2(20) NOT NULL,
    MENU_NAME VARCHAR2(50) NOT NULL,
    MENU_PRICE NUMBER NOT NULL,
    MENU_TYPE VARCHAR2(20)
);

SELECT * FROM BR_MEMBER_TBL;

CREATE TABLE BR_NOTICE_TBL (
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_SUBJECT VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT VARCHAR2(1500) NOT NULL,
    NOTICE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    NOTICE_WRITER VARCHAR2(20) NOT NULL,
    ANSWER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

SELECT * FROM BR_NOTICE_TBL;

DROP TABLE BR_NOTICE_TBL;

DROP SEQUENCE SEQ_NOTICENO;

CREATE SEQUENCE SEQ_NOTICENO;
--START WITH 1
--INCREMENT BY 1
--MAXVALUE 10000
--NOCYCLE
--NOCACHE;

SELECT * FROM USER_SEQUENCES;

commit;
